= Liminix
Daniel Barlow
:doctype: book
:toc: left

include::intro.adoc[]

include::tutorial.adoc[]

include::installation.adoc[]

= For Administrators

include::configuration.adoc[]

include::admin.adoc[]

include::development.adoc[]

include::modules.adoc[]

include::code-of-conduct.adoc[]

[appendix]
= Supported hardware

== Recommended devices

For development, the supported GL.iNet devices are all good choices if
you can find them, as they have a builtin "debrick" procedure in the
boot monitor and are also comparatively simple to attach serial cables
to (soldering not required), so are lower-risk than some other devices.

For a more powerful device, something with an ath10k wireless would be
the safe bet, or the Linksys E8450 which seems popular in the OpenWrt
community.

include::hardware.adoc[]

[appendix]
= Module and service options

include::module-options-generated.inc.adoc[]

[appendix]
= Outputs

*Outputs* are artefacts that can be installed somehow on a
target device, or "installers" which run on the target device to perform
the installation.

There are different outputs because different target devices need
different artefacts, or have different ways to get that artefact
installed. The options available for a particular device are described
in the section for that device.

include::outputs-generated.inc.adoc[]
